version: '3.8'

# Load environment variables from .env.docker file
# Copy .env.docker.example to .env.docker and configure your credentials

services:
  mindsdb-streamlined:
    build:
      context: .
      dockerfile: Dockerfile.streamlined
    container_name: mindsdb-streamlined
    env_file:
      - .env.docker  # Load credentials from .env.docker file
    ports:
      - "47334:47334"  # HTTP API
    environment:
      - MINDSDB_STORAGE_DIR=/home/mindsdb/data
      - MINDSDB_CONFIG_PATH=/home/mindsdb/config.json
      - MINDSDB_APIS=http
      - MINDSDB_DOCKER_ENV=True
      - MINDSDB_ENABLED_HANDLERS=airtable,supabase,gmail,google_analytics,lightwood,huggingface,huggingface_api,langchain,langchain_embedding,pgvector,postgres,sheets,s3,minds_endpoint,rag
      - MINDSDB_LOG_LEVEL=INFO
      # Credential environment variables (set these in your .env file)
      - MINDS_API_KEY=${MINDS_API_KEY:-}
      - AIRTABLE_API_KEY=${AIRTABLE_API_KEY:-}
      - HUGGING_FACE_API_KEY=${HUGGING_FACE_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - SUPABASE_POSTGRES_URL=${SUPABASE_POSTGRES_URL:-}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
      - S3_BUCKET_URL=${S3_BUCKET_URL:-}
    volumes:
      - mindsdb_data:/home/mindsdb/data
      - ./config-streamlined.json:/home/mindsdb/config.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:47334/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  mindsdb_data:
    driver: local